create table cargo (id bigint not null auto_increment, nome varchar(255) not null, setor_id bigint not null, primary key (id)) engine=InnoDB;
create table setor (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table trabalhador (id bigint not null auto_increment, cpf integer not null, nome varchar(255) not null, cargo_id bigint, setor_id bigint not null, primary key (id)) engine=InnoDB;
alter table cargo add constraint FKedraeswjtf0nb6oyj80xga89 foreign key (setor_id) references setor (id);
alter table trabalhador add constraint FKo7wx5vqjsh8mlhj3b61b0lsa9 foreign key (cargo_id) references cargo (id);
alter table trabalhador add constraint FKmcc5nbbos4jf0ir8o36atu5qr foreign key (setor_id) references setor (id);
insert into setor (id, nome) values (1, 'Tecnologia');
insert into setor (id, nome) values (2, 'Administração');
insert into cargo (id, nome, setor_id) values (1, 'Desenvolvedor', 1);
insert into cargo (id, nome, setor_id) values (2, 'Gerente', 2);
insert into trabalhador (id, nome, cpf, setor_id, cargo_id) values (1, 'Marcelo', 773, 1, 1);
insert into trabalhador (id, nome, cpf, setor_id, cargo_id) values (2, 'Ingrid', 521, 2, 2);
create table cargo (id bigint not null auto_increment, nome varchar(255) not null, setor_id bigint not null, primary key (id)) engine=InnoDB;
create table setor (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table trabalhador (id bigint not null auto_increment, cpf integer not null, nome varchar(255) not null, cargo_id bigint, setor_id bigint not null, primary key (id)) engine=InnoDB;
alter table cargo add constraint FKedraeswjtf0nb6oyj80xga89 foreign key (setor_id) references setor (id);
alter table trabalhador add constraint FKo7wx5vqjsh8mlhj3b61b0lsa9 foreign key (cargo_id) references cargo (id);
alter table trabalhador add constraint FKmcc5nbbos4jf0ir8o36atu5qr foreign key (setor_id) references setor (id);
insert into setor (id, nome) values (1, 'Tecnologia');
insert into setor (id, nome) values (2, 'Administração');
insert into cargo (id, nome, setor_id) values (1, 'Desenvolvedor', 1);
insert into cargo (id, nome, setor_id) values (2, 'Gerente', 2);
insert into trabalhador (id, nome, cpf, setor_id, cargo_id) values (1, 'Marcelo', 773, 1, 1);
insert into trabalhador (id, nome, cpf, setor_id, cargo_id) values (2, 'Ingrid', 521, 2, 2);
